@baseUrl=http://localhost:3005/api/user
@baseUrlDeepChat=http://deep-chat.com/api/user

POST {{baseUrl}}/create
Content-Type: application/json

{
  "username": "too",
  "name": "reality",
  "password": "loselose"
}

###

@herokuUrl=http://deep-chat-backend.herokuapp.com/api/user

POST {{baseUrlDeepChat}}/create
Content-Type: application/json

{
  "username": "too",
  "name": "reality",
  "password": "loselose"
}