@baseUrl=http://localhost:3005/api/user
@baseUrlDeepChat=http://backend.deep-chat.com/api/user
@cookie=token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjYTBjMDhiNGRkM2RiNDAyNDI4NWM4ZiIsImlhdCI6MTU1NDAzOTEwOX0.SfvBPgV-0X3fHmXD3oNUBW7OKfSgJ5yKC4cR3czo_tA

POST http://backend.deep-chat.com/api/auth/login
Content-Type: application/json

{
  "username": "woo",
  "password": "123"
}
###

GET {{baseUrlDeepChat}}/5bbf580216fe8930b052fede
Cookie: {{cookie}}
###
GET {{baseUrlDeepChat}}
Cookie: {{cookie}}
###
POST {{baseUrl}}/create
Content-Type: application/json

{
  "username": "too",
  "name": "reality",
  "password": "loselose"
}

###

POST {{baseUrlDeepChat}}/create
Content-Type: application/json

{
  "name": "raa",
  "username": "zorr0",
  "password": "ror"
}

###
PUT {{baseUrlDeepChat}}/edit
Content-Type: application/json
Cookie: {{cookie}}

{
  "id": "5ca0c08b4dd3db4024285c8f",
  "name": "zzz"
}

###

DELETE {{baseUrlDeepChat}}/delete
Content-Type: application/json
Cookie: {{cookie}}

{
  "id": "5c9f6451fb695a36c4a02075"
}

###

@herokuUrl=http://deep-chat-backend.herokuapp.com/api/user

POST {{baseUrlDeepChat}}/create
Content-Type: application/json

{
  "username": "woo",
  "name": "woo",
  "password": "123"
}